### ISSUE TITLE
IPv6 Nodes

### ISSUE THREAD

**Issue by juliaszone** [ditatompel/xmr-remote-nodes#84]
Hi, I run 2 IPv6 enabled nodes and I saw that only IPv4 is supported by the website.
Are there any plans for IPv6 support?

**Comment by juliaszone** [comment]
If IPv6 support is added, I believe it would also be nice to be able to filter for IPv6/IPv4/Dualstack nodes...

**Comment by ditatompel** [comment]
Thank you for the advice. I will try to implement that.

However, it doesn't look like it will happen anytime soon because most of the "probers" I have don't have (or explicitly disable) IPv6.

My estimate is that it will take around 1 to 2 months before we can implement and carry out testing.

**Comment by ditatompel** [comment]
Hi @juliaszone , I've change the code to accept IPv6 node and enabling IPv6 on one of the probers (linode). Can you please try add your nodes to see how it goes?

**Comment by juliaszone** [comment]
> Hi @juliaszone , I've change the code to accept IPv6 node and enabling IPv6 on one of the probers (linode). Can you please try add your nodes to see how it goes?

I tried to add it by domain, but it says it already exists. Those still show up as an IPv4 despite being dual stack.

I would show IPv6 then IPv4 address in the list like so:
![image](https://github.com/user-attachments/assets/401b4be6-142f-412d-8f1d-270293f9de18)
And now if a node has no IPv4:
![image](https://github.com/user-attachments/assets/03faccf2-b697-4e37-9c19-03f52e377048)
same for if a node has no IPv6:
![image](https://github.com/user-attachments/assets/81420de5-4105-431d-b706-11b258c03883)
I would also apply it exactly like that to the "Public IP" field in the "Probe Logs". The code could be reused easily.
For nodes that have been added using an IP address, I'd propose a removal of the "Public IP" fields in the list and on the logs.

I have tried adding IPv6 addresses, and it worked. They can be removed now.
https://xmr.ditatompel.com/remote-nodes/logs/?node_id=272
https://xmr.ditatompel.com/remote-nodes/logs/?node_id=273
A problem: IPv6 addresses when in URL/Port notation are to be put in square brackets:
![image](https://github.com/user-attachments/assets/c6f24778-8479-4d9e-a3bf-0492a612ffb2)
So, correct it would be [2a02:810d:b5bf:ece0::1:180]:18089.

A nice feature for dualstack nodes would be to crawl it on IPv4 and IPv6. If either is broken, then display it like this:
![image](https://github.com/user-attachments/assets/e75aec11-d161-4f2d-89f9-d23a59bb7002)

**Comment by juliaszone** [comment]
After some downtime of my nodes, they showed up as IPv6. Then now, it changed back to IPv4 for one node.

**Comment by ditatompel** [comment]
>  they showed up as IPv6. Then now, it changed back to IPv4 for one node.

If you have more than one A and/or AAAA DNS record, the current cycle and the next cycle may display different IP address. It depends on the first IP address obtained from the hostname lookup.

Therefore, I removed the IP address information from the table (but still exists from API call result) and replaced it with information about whether the host only supports IPv6 or not (61cc98e). So, if the submitted node is IPv6 address (or domain name that doesn't have IPv4) it will show **IPV6 only** info.

Speaking of IP addresses, maybe I could add an "IP lookup" button or something like that so that visitors can get that information only when needed. But I can't promise that it will be available anytime soon.

> A nice feature for dualstack nodes would be to crawl it on IPv4 and IPv6.

I wouldn't implement something like that. Performing RPC calls for every A/AAAA record for each node would take many times more resources than it needs to.

> I have tried adding IPv6 addresses, and it worked. They can be removed now.
> https://xmr.ditatompel.com/remote-nodes/logs/?node_id=272
> https://xmr.ditatompel.com/remote-nodes/logs/?node_id=273

Sure, will do. Thanks for your help!
